---
- name: Prepare k3s nodes
  hosts: k3s_cluster
  gather_facts: true
  become: true
  roles:
    - role: prereq
      become: true
    - role: download
      become: true

- name: Setup K3S server
  hosts: master
  become: true
  roles:
    - role: k3s_server

- name: Configure k3s cluster
  hosts: master
  become: true
  roles:
    - role: k3s_server_post
