---
- name: Pre-req steps for k3s cluster
  hosts: all
  gather_facts: true
  become: true
  roles:
    - role: prereq

- name: Setup K3S server
  hosts: all
  become: true
  roles:
    - role: k3s_server
