---
############# pre-req role variables ################

# timezone to make all nodes on the same system time
system_timezone: Etc/UTC

############# k3s_server role variables #############
k3s_version: v1.29.2+k3s1
systemd_dir: /etc/systemd/system

# The IP on which the node is reachable in the cluster.
k3s_node_ip: "{{ ansible_facts['default_ipv4']['address'] }}"

# Disable the taint manually by setting: k3s_master_taint = false
k3s_master_taint: "{{ true if groups['node'] | default([]) | length >= 1 else false }}"

# these arguments are recommended for servers as well as agents:
extra_args: "--node-ip={{ k3s_node_ip }}"

# apiserver_endpoint is virtual ip-address which will be configured on each master, make sure this ips is in the same cidr block as yours
apiserver_endpoint: "192.168.1.222"

# change these to your liking, the only required are: --disable servicelb, --tls-san {{ apiserver_endpoint }}
# the contents of the if block is also required if using calico or cilium
extra_server_args: >-
  {{ extra_args }}
  {{ '--node-taint node-role.kubernetes.io/master=true:NoSchedule' if k3s_master_taint else '' }}
  --tls-san {{ apiserver_endpoint }}
  --disable servicelb
  --disable traefik

kube_vip_tag_version: "v0.7.2"

# metallb type frr or native
metal_lb_type: "native"

# metallb mode layer2 or bgp
metal_lb_mode: "layer2"

# image tag for metal lb
metal_lb_speaker_tag_version: "v0.14.3"
metal_lb_controller_tag_version: "v0.14.3"

# metallb ip range for load balancer, make sure these ips are in the same cidr block as yours
metal_lb_ip_range: "192.168.1.60-192.168.1.70"

############# k3s_agent role variables #############
extra_agent_args: >-
  {{ extra_args }}
